# Copyright 2026 Lucas Wendland
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""MultiCartPoleVecEnv — N cartpoles in ONE gz sim, batched as SB3 VecEnv.

Implements the SB3 VecEnv interface against the multi-agent CartPole
world generated by `scripts/generate_multi_cartpole_world.py`. The
plugin instance for each cartpole publishes / subscribes on indexed
topics (`/env/action_<i>`, `/env/state_<i>`); this class fans actions
out to N publishers and joins N state replies before returning.

**Group-reset semantics** (matches the user's TASKS.md spec):
    A single env.reset() call triggers a world-control reset, which
    propagates to every cartpole's plugin in one shot. Individual
    agent failures don't fire a reset — terminated agents simply stop
    moving (the plugin publishes cmd_vel=0 during their grace period)
    and contribute 0 reward until the next group reset.

**When to reset** (decided by the VecEnv internally):
    - All N agents have terminated (every pole tipped or every cart
      exceeded its X bound), OR
    - max_episode_steps elapsed since the last group reset.

Both conditions count toward the per-agent `done` flag SB3 receives. SB3
PPO consumes the (N, obs_dim) batch each step and treats agents that
terminated mid-episode the standard way — the rollout buffer marks them
as done and credits no reward beyond the termination tick.
"""

import math
import os
import threading
import time
from typing import Any
from typing import Optional

from gymnasium.spaces import Box
from gymnasium.spaces import Discrete
from gz.msgs10.boolean_pb2 import Boolean
from gz.msgs10.entity_factory_pb2 import EntityFactory
from gz.msgs10.entity_pb2 import Entity
from gz.msgs10.float_v_pb2 import Float_V
from gz.msgs10.model_pb2 import Model as ModelMsg
from gz.transport13 import AdvertiseMessageOptions
from gz.transport13 import Node
import numpy as np
from stable_baselines3.common.vec_env import VecEnv

from ..backend.nodes import world_control


POLE_ANGLE_THRESHOLD = 0.20944
CART_POSITION_THRESHOLD = 2.4
DEFAULT_MAX_EPISODE_STEPS = 500
DEFAULT_FRAME_SKIP = 5

# Grid layout constants — kept in sync with bringup's
# scripts/spawn_multi_cartpoles.py so the launch-time spawn and the
# env's reset-time respawn place agents at the same coordinates.
_X_SPACING = 3.0
_Y_SPACING = 8.5
# Per-call timeout for gz Create/Remove service requests.
_GZ_SERVICE_TIMEOUT_MS = 500
# Brief settle between the bulk delete and the bulk re-create.
_REMOVE_TO_CREATE_DELAY = 0.05


class MultiCartPoleVecEnv(VecEnv):
    """N-cartpoles-in-one-sim vec env, SB3-compatible.

    Parameters
    ----------
    n_agents : int
        Number of cartpoles in the world. Must match the world SDF
        produced by `generate_multi_cartpole_world.py`.
    world_name : str
        Name of the gz world (default: `cartpole_multi`).
    max_episode_steps : int
        Steps before a forced group reset (default 500, matching CartPole-v1).
    reset_timeout / step_timeout : float
        Per-call seconds to wait for the gz sim's state publishes.
    """

    metadata = {"render_modes": [], "render_fps": 30}

    def __init__(self, n_agents: int = 4,
                 world_name: str = "cartpole_multi",
                 max_episode_steps: int = DEFAULT_MAX_EPISODE_STEPS,
                 frame_skip: int = DEFAULT_FRAME_SKIP,
                 reset_timeout: float = 3.0,
                 step_timeout: float = 1.0):
        if n_agents < 1:
            raise ValueError("n_agents must be >= 1")
        self.n_agents = n_agents
        self.world_name = world_name
        self.max_episode_steps = max_episode_steps
        self.frame_skip = frame_skip
        self.reset_timeout = reset_timeout
        self.step_timeout = step_timeout

        # Canonical CartPole-v1 spaces, one per agent. VecEnv stores them
        # singularly (action_space + observation_space are per-env, NOT
        # batched — SB3 takes care of N-way batching internally).
        observation_space = Box(
            low=np.array([-4.8, float("-inf"), -0.41887903, float("-inf")],
                         dtype=np.float32),
            high=np.array([4.8, float("inf"), 0.41887903, float("inf")],
                          dtype=np.float32),
            shape=(4,),
            dtype=np.float32,
        )
        action_space = Discrete(2)
        super().__init__(n_agents, observation_space, action_space)

        # Per-agent state cache + threading sync. The plugin publishes
        # /env/state_i once per frame_skip ticks; we collect all N events
        # before treating env.step() as complete.
        self._latest_states = np.zeros((n_agents, 4), dtype=np.float32)
        self._state_events = [threading.Event() for _ in range(n_agents)]
        self._state_lock = threading.Lock()

        # Per-agent done state — once an agent fails, we hold its done
        # flag through to the next group reset. SB3 sees done=True only
        # on the tick the agent flips from alive to dead; subsequent
        # ticks it sees done=False with zero reward, which is fine for
        # PPO's GAE bookkeeping (the terminated transition's value
        # bootstrap is correct).
        self._dones = np.zeros(n_agents, dtype=bool)
        self._steps_since_reset = 0
        self._current_episode = 0
        self._episode_rewards = np.zeros(n_agents, dtype=np.float32)

        # Verbose env var consistent with the single-agent env.
        self._debug = os.environ.get(
            "GAZEBO_GYM_VERBOSE", "false").lower() in ("1", "true", "yes", "on")

        # gz transport — N action publishers (Float_V to /env/action_<i>),
        # N joint_state subscribers. The action topic is consumed by the
        # WORLD-level controller plugin (`cartpole_world_controller`),
        # NOT by the per-model plugin — model-level plugins don't load
        # for dynamically-spawned cartpoles, so we route actuation
        # through a world-level plugin that survives the dynamic spawn
        # lifecycle.
        self._action_nodes = []
        self._action_pubs = []
        for i in range(n_agents):
            node = Node()
            topic = f"/env/action_{i}"
            pub = node.advertise(topic, Float_V, AdvertiseMessageOptions())
            self._action_nodes.append(node)
            self._action_pubs.append(pub)

        # Frame-skip emulation: joint_state publishes at 100 Hz (every
        # physics tick); we only release step_wait after frame_skip
        # joint_state messages arrive, mirroring CartPole-v1's 50 ms
        # decision interval.
        self._joint_state_counts = np.zeros(n_agents, dtype=int)

        # Sensor reads come from gz's joint_state topic directly, NOT from
        # the plugin's /env/state_<i> path. Reason: with dynamically-spawned
        # models, the plugin's _on_joint_state callback isn't firing reliably
        # and /env/state_<i> publishes stale zeros — confirmed empirically by
        # subscribing to both topics. The plugin still handles action→cmd_vel
        # fine; we just bypass its broken sensor-cache layer.
        self._joint_state_nodes = []
        for i in range(n_agents):
            node = Node()
            topic = f"/world/{world_name}/model/cartpole_{i}/joint_state"
            node.subscribe(ModelMsg, topic,
                           self._make_joint_state_callback(i))
            self._joint_state_nodes.append(node)

        self._world_control = world_control.WorldController(
            world_name, steps_per_action=0)

        print(f"[MultiCartPoleVecEnv] ready (world={world_name!r}, "
              f"n_agents={n_agents}, frame_skip={frame_skip})")

    def _make_joint_state_callback(self, idx: int):
        """Direct sensor read from gz joint_state — bypass for broken plugin."""
        def _cb(msg):
            cart_pos = cart_vel = pole_ang = pole_vel = 0.0
            for joint in msg.joint:
                if joint.name == "slider_to_cart":
                    cart_pos = joint.axis1.position
                    cart_vel = joint.axis1.velocity
                elif joint.name == "cart_to_pole":
                    pole_ang = joint.axis1.position
                    pole_vel = joint.axis1.velocity
            with self._state_lock:
                self._latest_states[idx] = [
                    float(cart_pos), float(cart_vel),
                    float(pole_ang), float(pole_vel),
                ]
                self._joint_state_counts[idx] += 1
                if self._joint_state_counts[idx] >= self.frame_skip:
                    fire = not self._state_events[idx].is_set()
                    self._state_events[idx].set()
                else:
                    fire = False
            if self._debug and fire:
                print(f"[MultiCartPoleVecEnv] joint_state recv agent={idx} "
                      f"obs={list(self._latest_states[idx])}")
        return _cb

    # ------------------------------------------------------------------ #
    # VecEnv API
    # ------------------------------------------------------------------ #

    def reset(self) -> np.ndarray:
        # NOTE on reset semantics: we don't call world_control.reset().
        # That sends `reset.all = True`, which reverts gz to the SDF-
        # loaded state — for the multi-agent setup that means the EMPTY
        # cartpole_multi.sdf world, and every dynamically-spawned
        # cartpole gets wiped. Instead we delete + recreate each
        # cartpole via the gz Create/Remove services, leaving the world
        # itself untouched. ~50–100 ms per agent.
        self._recreate_all_agents()
        if not self._wait_all_states(self.reset_timeout):
            print("[MultiCartPoleVecEnv] WARN: reset state wait timed out")

        if self._steps_since_reset > 0:
            print(
                f"[EpisodeSummary] ep={self._current_episode} "
                f"steps={self._steps_since_reset} "
                f"agents_done={int(self._dones.sum())}/{self.n_agents} "
                f"mean_reward={float(self._episode_rewards.mean()):.1f}"
            )

        self._dones[:] = False
        self._steps_since_reset = 0
        self._current_episode += 1
        self._episode_rewards[:] = 0.0
        return self._latest_states.copy()

    def step_async(self, actions: np.ndarray) -> None:
        # SB3 calls step_async then step_wait. We publish Float_V on
        # /env/action_<i> (consumed by the world-level controller plugin)
        # and block on frame_skip-many joint_state replies in step_wait.
        actions = np.asarray(actions).reshape(self.n_agents)
        with self._state_lock:
            self._joint_state_counts[:] = 0
            for ev in self._state_events:
                ev.clear()
        for i in range(self.n_agents):
            msg = Float_V()
            msg.data.append(float(int(actions[i])))
            self._action_pubs[i].publish(msg)
        self._pending_step_start = time.perf_counter()

    def step_wait(self):
        if not self._wait_all_states(self.step_timeout):
            print("[MultiCartPoleVecEnv] WARN: step state wait timed out")
            # Force a reset on timeout — safer than returning stale data.
            self._dones[:] = True

        with self._state_lock:
            obs = self._latest_states.copy()

        # CartPole-v1 reward + termination, per agent.
        rewards = np.zeros(self.n_agents, dtype=np.float32)
        new_dones = np.zeros(self.n_agents, dtype=bool)
        for i in range(self.n_agents):
            if self._dones[i]:
                # Already-dead agents contribute zero reward and stay
                # marked done until group reset. SB3 still sees done=False
                # here so it doesn't reset us per-agent (we only return
                # done=True on the tick of the *transition* to terminal).
                continue
            cart_pos, _cart_vel, pole_angle, _pole_ang_vel = obs[i]
            terminated = (abs(pole_angle) > POLE_ANGLE_THRESHOLD
                          or abs(cart_pos) > CART_POSITION_THRESHOLD)
            if terminated:
                new_dones[i] = True
                self._dones[i] = True
            else:
                rewards[i] = 1.0

        self._steps_since_reset += 1
        self._episode_rewards += rewards
        # Group-reset trigger: when EVERY agent has terminated OR we hit
        # max steps, the next step_wait flips all dones to True and SB3's
        # rollout loop will call reset().
        if self._dones.all() or self._steps_since_reset >= self.max_episode_steps:
            new_dones[:] = True
            self._dones[:] = True

        infos = [{} for _ in range(self.n_agents)]
        # SB3 reads "TimeLimit.truncated" from info dict to distinguish
        # truncation from natural termination. Mark it only on the
        # truncation case (max_steps hit AND the agent was still alive).
        if self._steps_since_reset >= self.max_episode_steps:
            for i in range(self.n_agents):
                infos[i]["TimeLimit.truncated"] = True

        if self._debug:
            step_ms = (time.perf_counter() - self._pending_step_start) * 1000.0
            print(
                f"[MultiCP step {self._steps_since_reset}] "
                f"alive={int((~self._dones).sum())}/{self.n_agents} "
                f"mean_reward={float(rewards.mean()):.2f} "
                f"step_ms={step_ms:.1f}"
            )

        return obs, rewards, new_dones, infos

    def close(self) -> None:
        # gz transport nodes shut down on GC.
        pass

    # VecEnv abstract methods we don't really use but must implement —
    # SB3's wrappers (VecMonitor, etc.) sometimes call them. Return
    # sensible defaults.

    def get_attr(self, attr_name: str, indices=None):
        if indices is None:
            indices = range(self.n_agents)
        return [getattr(self, attr_name, None) for _ in indices]

    def set_attr(self, attr_name: str, value: Any, indices=None) -> None:
        setattr(self, attr_name, value)

    def env_method(self, method_name: str, *method_args,
                   indices=None, **method_kwargs):
        if indices is None:
            indices = range(self.n_agents)
        method = getattr(self, method_name)
        return [method(*method_args, **method_kwargs) for _ in indices]

    def env_is_wrapped(self, wrapper_class, indices=None):
        if indices is None:
            indices = range(self.n_agents)
        return [False for _ in indices]

    def seed(self, seed: Optional[int] = None):
        # Determinism for this vec env is controlled by the gz sim seed,
        # which we don't expose here. Returning [seed] keeps SB3 happy.
        return [seed for _ in range(self.n_agents)]

    # ------------------------------------------------------------------ #
    # Helpers
    # ------------------------------------------------------------------ #

    def _grid_position(self, index: int) -> tuple:
        """(x, y) for cartpole #index — kept in sync with the launch spawner."""
        n = self.n_agents
        cols = math.ceil(math.sqrt(n))
        rows = math.ceil(n / cols)
        col = index % cols
        row = index // cols
        x = (col - (cols - 1) / 2.0) * _X_SPACING
        y = (row - (rows - 1) / 2.0) * _Y_SPACING
        return x, y

    def _render_cartpole_sdf(self, index: int) -> str:
        """Build the same SDF template as bringup's spawn_multi_cartpoles.py."""
        name = f"cartpole_{index}"
        return (
            f"""<sdf version="1.8">
              <model name="{name}">
                <self_collide>true</self_collide>
                <include merge="true">
                  <uri>package://gazebo_gymnasium_resources/models/cartpole</uri>
                </include>
                <plugin filename="gz-sim-python-system-loader-system"
                        name="gz::sim::systems::PythonSystemLoader">
                  <module_name>multi_cartpole_learner</module_name>
                  <agent_name>{name}</agent_name>
                  <agent_index>{index}</agent_index>
                  <frame_skip>5</frame_skip>
                </plugin>
                <joint name="world_to_slider" type="fixed">
                  <parent>world</parent>
                  <child>slider</child>
                </joint>
              </model>
            </sdf>"""
        )

    def _recreate_all_agents(self) -> None:
        """Delete + recreate every cartpole in the running world.

        Replaces world_control.reset() — see the note in reset(). Uses
        the same gz Create/Remove services as the launch-time spawner.
        State events are cleared so the post-recreate _wait_all_states
        call waits for fresh initial states from the re-instantiated
        plugins.
        """
        for ev in self._state_events:
            ev.clear()

        transport = self._world_control.world_control_node
        remove_service = f"/world/{self.world_name}/remove"
        create_service = f"/world/{self.world_name}/create"

        for i in range(self.n_agents):
            req = Entity()
            req.name = f"cartpole_{i}"
            req.type = Entity.MODEL
            transport.request(remove_service, req, Entity, Boolean,
                              _GZ_SERVICE_TIMEOUT_MS)

        time.sleep(_REMOVE_TO_CREATE_DELAY)

        for i in range(self.n_agents):
            x, y = self._grid_position(i)
            req = EntityFactory()
            req.sdf = self._render_cartpole_sdf(i)
            req.name = f"cartpole_{i}"
            req.pose.position.x = x
            req.pose.position.y = y
            req.pose.position.z = 0.0
            transport.request(create_service, req, EntityFactory, Boolean,
                              _GZ_SERVICE_TIMEOUT_MS)

        # World reset / entity churn sometimes leaves the sim paused.
        # Explicit unpause guarantees physics ticks after reset, so the
        # plugins' post_update fires and we get state replies.
        self._world_control.unpause()

        # Settle for cross-process gz-transport discovery — the env's
        # already-existing /env/action_<i> publishers need a moment to
        # be paired with the freshly-spawned plugins' new subscribers.
        # 0.3s is the steady-state pairing latency observed empirically.
        time.sleep(0.3)

        # No ping action needed — joint_state publishes at 100 Hz
        # independent of actions, so the next _wait_all_states will
        # see fresh joint_state arriving within ~10 ms (per agent)
        # regardless of whether the env has sent any action yet.
        with self._state_lock:
            self._joint_state_counts[:] = 0

    def _wait_all_states(self, timeout: float) -> bool:
        """Block until every agent's /env/state_i callback has fired."""
        deadline = time.perf_counter() + timeout
        for i, ev in enumerate(self._state_events):
            remaining = deadline - time.perf_counter()
            if remaining <= 0 or not ev.wait(timeout=remaining):
                received = [j for j, e in enumerate(self._state_events)
                            if e.is_set()]
                missing = [j for j, e in enumerate(self._state_events)
                           if not e.is_set()]
                print(
                    f"[MultiCartPoleVecEnv] _wait_all_states timeout after "
                    f"{timeout:.1f}s: waiting on agent {i}, "
                    f"received={received} missing={missing}"
                )
                return False
        return True
