#!/usr/bin/env python3
# Copyright 2026 Lucas Wendland
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate six additional line_follower track shapes, alongside the existing rectangle.

`generate_line_track.py` builds one fixed rectangular loop
(`models/line_track/`). This script writes six SIBLING model directories
(`line_track_<shape>/`) from the shared geometry in
`gazebo_gymnasium_bridge.envs.line_track_shapes` -- the same builder
functions `_build_world` imports at runtime to pick a spawn point for
whichever shape an agent draws, kept in one place rather than duplicated.
Leaves the original `line_track/` and its generator completely untouched.

Motivation: `line_follower` trained against one fixed track shape and one
fixed spawn point for this project's entire history -- real risk of the
policy partially memorizing a trajectory rather than learning to actually
track a visible line. These six shapes are the population-based variety
`AgentSpec.track_shape_choices` (agent_spec.py) draws from, one per agent,
so a single training run's population sees real shape diversity rather
than the same corner sequence every time.

Run: pixi run python scripts/generate_line_tracks.py
"""

from pathlib import Path
import sys

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "gazebo_gymnasium_bridge"))

from gazebo_gymnasium_bridge.envs.line_track_shapes import PRESETS  # noqa: E402
from gazebo_gymnasium_bridge.envs.line_track_shapes import TRACK_HEIGHT  # noqa: E402
from gazebo_gymnasium_bridge.envs.line_track_shapes import TRACK_WIDTH  # noqa: E402

MODELS_ROOT = PROJECT_ROOT / "gazebo_gymnasium_examples" / "gazebo_gymnasium_resources" / "models"

MATERIAL = """      <material>
        <ambient>0.02 0.02 0.02 1</ambient>
        <diffuse>0.02 0.02 0.02 1</diffuse>
        <specular>0.0 0.0 0.0 1</specular>
      </material>"""

DESCRIPTIONS = {
    "square": (
        "Rounded square loop -- extra corner-angle variety alongside the original rectangle."
    ),
    "triangle": (
        "Equilateral triangle loop -- the sharpest corners (60 degree "
        "interior angle) among the standard shapes."
    ),
    "pentagon": "Regular pentagon loop -- five 108-degree corners.",
    "zigzag": (
        "Closed loop with a sawtooth top edge -- repeated sharp direction "
        "reversals, a genuinely different challenge from a single-shape corner."
    ),
    "circle": "Pure circular loop -- continuous curvature, no straights at all.",
    "racetrack": (
        "Stadium/obround loop -- two straights and two 180-degree "
        "semicircle ends, the classic running-track shape."
    ),
}


def _visual_box(name, pose, size):
    x, y, z, roll, pitch, yaw = pose
    sx, sy, sz = size
    return (
        f"      <visual name='{name}'>\n"
        f"        <pose>{x:.6f} {y:.6f} {z:.6f} {roll:.6f} {pitch:.6f} {yaw:.6f}</pose>\n"
        f"        <geometry>\n"
        f"          <box>\n"
        f"            <size>{sx:.6f} {sy:.6f} {sz:.6f}</size>\n"
        f"          </box>\n"
        f"        </geometry>\n"
        f"{MATERIAL}\n"
        f"      </visual>"
    )


def write_model(name, segments, description):
    model_dir = MODELS_ROOT / f"line_track_{name}"
    model_dir.mkdir(parents=True, exist_ok=True)

    visuals = "\n".join(
        _visual_box(f"seg_{i:03d}", pose, size) for i, (pose, size) in enumerate(segments)
    )
    sdf = f"""<?xml version="1.0"?>
<sdf version="1.8">
  <!-- Auto-generated by scripts/generate_line_tracks.py. Hand edits will be
       lost on regeneration; tune the preset function in
       gazebo_gymnasium_bridge/envs/line_track_shapes.py and re-run instead. -->
  <model name="line_track_{name}">
    <static>true</static>
    <link name="track">
      <!-- One static link holds every track segment as a <visual>. No
           <collision> blocks: the line is a vision target only -- the
           rover should never feel friction against it. -->
{visuals}
    </link>
  </model>
</sdf>
"""
    (model_dir / "model.sdf").write_text(sdf)

    config = f"""<?xml version="1.0"?>
<model>
  <name>line_track_{name}</name>
  <version>1.0</version>
  <sdf version="1.8">model.sdf</sdf>

  <author>
    <name>Lucas Wendland</name>
    <email>lwendlan@umd.edu</email>
  </author>

  <description>
    {description} Same visual style and scale as models/line_track/
    ({TRACK_WIDTH} m wide, {TRACK_HEIGHT} m thick) -- part of the
    track_shape_choices population-based track-shape set for line_follower
    (see docs/domain_randomization.md).
  </description>
</model>
"""
    (model_dir / "model.config").write_text(config)
    return model_dir, len(segments)


def main():
    for name, (builder, _model_dir_name) in PRESETS.items():
        if name == "rectangle":
            continue  # models/line_track/ already exists, untouched by this script
        segs = builder()
        model_dir, n = write_model(name, segs, DESCRIPTIONS[name])
        print(f"{name}: {n} segments -> {model_dir.relative_to(PROJECT_ROOT)}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
