#!/usr/bin/env python3
# Copyright 2026 Lucas Wendland
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Generate `rover_line_bare` from `rover_bare`, correcting the camera mount.

`rover_bare` is left exactly as it is, because `line_follower` and every
number ever recorded against it depend on that model. This writes a second
model that differs from it ONLY in the camera, and generating it (rather than
copying 500 lines by hand) keeps the delta legible and re-appliable.

Two corrections, each measured against the physical rover.

The camera MOUNT is left exactly as `rover_bare` has it, after a wrong turn
worth recording. The optical +X axis resolves to body -Y (SDF's
R = Rz(yaw)*Ry(pitch)*Rx(roll) puts it at (0, -0.707, -0.707)) while positive
wheel commands drive the chassis along body +Y, so the camera appears to face
backwards. Re-aiming it at +Y instead renders the rover's own chassis -- the
lens sits just beyond the trailing caster, and +Y looks straight over the
drive wheels. Measured world poses at spawn, travelling toward -X:

    drive wheels x=-0.986 (leading) | base -0.925 | caster -0.817 | lens -0.776

The lens is mounted past the caster looking outward, which is where the real
rover's camera is bolted. So the mount is right and the DRIVE SIGN is wrong:
the real rover drives caster-first, toward the view. `rover_line`'s action map
negates the wheel commands to match, and this model keeps the original pose.

1. **64x64 @ 60 deg -> 64x48 @ 56.7 deg.** The real sensor is an OV2640 (XIAO
   ESP32S3), 4:3 at 68 deg diagonal => 56.7 deg horizontal, 44.1 deg vertical.
   Rendering square at 60 deg gave the policy a wider, differently-shaped
   view than the hardware will ever produce, and forced the deployment
   pipeline to squash a 4:3 frame into a square one. 640x480 -> 64x48 is an
   exact 10x downscale, so sim and hardware now agree on aspect.
2. **30 Hz -> 15 Hz.** Matches the camera firmware's STREAM_FPS default.

Height is NOT changed: the camera link measures 0.1388 m above ground in the
running simulation, against 0.14 m on the real rover.

Run: python scripts/make_rover_line_model.py
"""

import math
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MODELS = ROOT / "gazebo_gymnasium_examples" / "gazebo_gymnasium_resources" / "models"
SRC = MODELS / "rover_bare"
DST = MODELS / "rover_line_bare"

# OV2640, 68 degrees diagonal on a 4:3 frame.
DIAG_FOV_DEG = 68.0
_k = math.tan(math.radians(DIAG_FOV_DEG) / 2.0) / 5.0  # 3-4-5 diagonal
H_FOV = 2.0 * math.atan(4.0 * _k)
V_FOV = 2.0 * math.atan(3.0 * _k)
WIDTH, HEIGHT = 64, 48
UPDATE_HZ = 15

EDITS = [
    ("<horizontal_fov>1.047</horizontal_fov>", f"<horizontal_fov>{H_FOV:.6f}</horizontal_fov>"),
    (
        "<width>64</width>\n            <height>64</height>",
        f"<width>{WIDTH}</width>\n            <height>{HEIGHT}</height>",
    ),
    ("<update_rate>30</update_rate>", f"<update_rate>{UPDATE_HZ}</update_rate>"),
    ("<model name='rover_bare'>", "<model name='rover_line_bare'>"),
]

CONFIG = f"""<?xml version="1.0"?>
<model>
  <name>rover_line_bare</name>
  <version>1.0</version>
  <sdf version="1.8">model.sdf</sdf>
  <description>
    `rover_bare` with the camera SENSOR matched to the physical rover's
    OV2640: the mount is unchanged (it is already correct -- see the
    generator script), and it renders {WIDTH}x{HEIGHT} at
    {math.degrees(H_FOV):.1f} deg horizontal / {math.degrees(V_FOV):.1f} deg
    vertical to match the OV2640's 4:3 frame,
    at {UPDATE_HZ} Hz to match the camera firmware. Generated by
    scripts/make_rover_line_model.py -- edit that, not this.
  </description>
</model>
"""


def main():
    sdf = (SRC / "model.sdf").read_text()
    for old, new in EDITS:
        if old not in sdf:
            raise SystemExit(f"pattern not found in rover_bare/model.sdf:\n  {old!r}")
        sdf = sdf.replace(old, new, 1)
    DST.mkdir(parents=True, exist_ok=True)
    (DST / "model.sdf").write_text(sdf)
    (DST / "model.config").write_text(CONFIG)

    h = 0.1388  # measured camera height above ground, in-sim
    near = h / math.tan(math.radians(45) + V_FOV / 2)
    far = h / math.tan(math.radians(45) - V_FOV / 2)
    print(f"wrote {DST.relative_to(ROOT)}")
    print(
        f"  hFOV {math.degrees(H_FOV):.2f} deg, vFOV {math.degrees(V_FOV):.2f} deg, "
        f"{WIDTH}x{HEIGHT} @ {UPDATE_HZ} Hz"
    )
    print(
        f"  ground visible {near:.3f} m -> {far:.3f} m ahead "
        f"(lookahead {far:.2f} m vs 0.40 m corner radius)"
    )


if __name__ == "__main__":
    main()
